name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
      
    - name: Create firebase.json
      run: |
        cat > firebase.json << 'EOF'
        {
          "hosting": {
            "public": ".",
            "ignore": [
              "firebase.json",
              "**/.*",
              "**/node_modules/**",
              "README.md",
              ".github/**"
            ],
            "rewrites": [
              {
                "source": "**/*.html",
                "destination": "/index.html"
              }
            ],
            "headers": [
              {
                "source": "**/*.@(css|js)",
                "headers": [
                  {
                    "key": "Cache-Control",
                    "value": "max-age=31536000"
                  }
                ]
              }
            ]
          }
        }
        EOF
        
    - name: Deploy to Firebase
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json
        firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --only hosting
